### PR TITLE
Use a single known_hosts file

### PR DESCRIPTION
**Pull request by jabl**
ssh cannot use multiple GlobalKnownHostsFile directives, only the first one
is used. Since a single known hosts file can contain pubkeys with different
types, using multiple known_hosts files brings no benefit.

### CODE REVIEW

**Comment by martbhell** [comment]
Thanks for the PR. 
I'm waiting on some unrelated things so we can test this on the test system.

**Comment by martbhell** [comment]
merge/conflict management done. Took your changes jabl and put in a new branch in this repo to sync in the change with the removal of ip_address variable. Now testing changes.

**Comment by martbhell** [comment]
After this change only the last pubkeys are used (ed25519).

This matches 3 times in ssh_known_hosts.yml:
 name='{{ item }}'

https://github.com/CSC-IT-Center-for-Science/ansible-role-sshd-host-keys/blob/1/known_hosts_fix/tasks/ssh_known_hosts.yml#L5-L26

More work needed to have it write all the types of host keys.
I have no idea right now how to get around it.

**Comment by jabl** [comment]
Yes, it seems the ansible known_hosts module doesn't understand having multiple key types for the same name. Simplest way to get around it is to just use the ed25519 keys and forget about rsa and ecdsa. Done in https://github.com/jabl/ansible-role-sshd-host-keys/commit/2914e63fa5f2f44829aa7dfb9a7dd2d3f20a9624 and https://github.com/jabl/ansible-role-sshd-host-keys/commit/1222e6dda6d53af61f1245c71fb522caf9a7c71d

**Comment by martbhell** [comment]
Merged into master now with 8a0408cfdea02e7d1f36e43314f8ec595b8cff2b

**Comment by martbhell** [comment]
ansible-pull ran nicely on one of io's (the test cluster) nodes and ssh works nicely to it without any MITM error messages.

I think we can finally close this?

**Comment by jabl** [comment]
Seems to work now, thanks!

**Pull request closed without merging**
